[versions]
agp = "7.2.2"
kotlin = "1.7.10"
ksp = "1.7.10-1.0.6"
javaRelease = "8"
jvmTarget = "1.8"
material = "1.6.1"
androidxActivity = "1.4.0"
androidxFragment = "1.5.1"
androidxLifecycle = "2.5.1"
androidxRoom = "2.4.3"
androidxArchCore = "2.1.0"
androidXStartup = "1.1.1"
bindables = "1.1.0"
hilt = "2.42"
retrofit = "2.9.0"
okHttp = "4.10.0"
sandwich = "1.3.0"
moshi = "1.13.0"
coroutines = "1.6.4"
whatIf = "1.1.1"
glide = "4.13.2"
glidePalette = "2.1.2"
bundler = "1.0.4"
transformationLayout = "1.1.1"
recyclerView = "1.2.1"
baseAdapter = "1.0.4"
androidRibbon = "1.0.4"
progressView = "1.1.3"
rainbow = "1.0.3"
timber = "5.0.1"
baselineProfiles = "1.2.0"
macroBenchmark = "1.1.0"
uiAutomator = "2.2.0"
truth = "1.0.1"
junit = "4.13.1"
turbine = "0.6.0"
robolectric = "4.4"
androidxTest = "1.3.0"
androidxTestJunit = "1.1.2"
androidTestRunner = "1.3.0-beta01"
espresso = "3.3.0"
mockitoKotlin = "2.2.0"
mockitoInline = "3.5.13"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "6.7.2" }
hilt-plugin = { id = "dagger.hilt.android.plugin", version = "hilt" }

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }

material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCore" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidXStartup" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
bindables = { module = "com.github.skydoves:bindables", version.ref = "bindables" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
sandwich = { module = "com.github.skydoves:sandwich", version.ref = "sandwich" }
retrofit = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
okhttp-mockserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
whatif = { module = "com.github.skydoves:whatif", version.ref = "whatIf" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-palette = { module = "com.github.florent37:glidepalette", version.ref = "glidePalette" }
bundler = { module = "com.github.skydoves:bundler", version.ref = "bundler" }
transformationLayout = { module = "com.github.skydoves:transformationlayout", version.ref = "transformationLayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
baseAdapter = { module = "com.github.skydoves:baserecyclerviewadapter", version.ref = "baseAdapter" }
rainbow = { module = "com.github.skydoves:rainbow", version.ref = "rainbow" }
androidRibbon = { module = "com.github.skydoves:androidribbon", version.ref = "androidRibbon" }
progressView = { module = "com.github.skydoves:progressview", version.ref = "progressView" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# unit test
junit = { module = "junit:junit", version.ref = "junit" }
mockito-kotlin  = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-inline  = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
android-test-runner = { module = "com.android.support.test:runner", version.ref = "androidTestRunner" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "baselineProfiles" }
macrobenchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "macroBenchmark" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }